name: Workflow to create an artifact
on:
  workflow_dispatch:
  push:

env:
  ARTIFACT_NAME: my_arti_name

jobs:
  test:
    runs-on: [ubuntu-latest, Linux, internal]

    steps:
      - name: Checkout code
      - uses: actions/checkout@v4.1.5

      - name: Upload artifact
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: Upload ${{ env.ARTIFACT_NAME }}
          path: ./${{ env.ARTIFACT_NAME }}
